### ISSUE TITLE
Module stopped working 

### ISSUE THREAD

**Issue by joorgejose** [xkik-dev/XKik#3]
So today my module stopped working for no reason. I have the right version of kik and xkik and the only tweak that works is the visual one. No fake camera or emojis.

**Comment by xkik-dev** [comment]
@joorgejose Hm, that's strange. I'm assuming it worked before since you mention it stopped.  Did you change any settings on xkik or your device before you noticed the issues? Also, I know you said you have the correct version but I just want you to double check since Google play sometimes decides to auto updates apps

**Comment by xixenz** [comment]
fake camera is not working  but the rest are fine
